// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvrbjuwocbbsaihluvmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52cmJqdXdvY2Jic2FpaGx1dm1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MzI3OTgsImV4cCI6MjA2NzUwODc5OH0.JNH0R2VlMIes11eho4GYKBKNZMDOc6ZSoRa9wkRaKco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});